#include "openbitstreamcommand.h"
#include "model/modellocator.h"
#include "parsers/bitstreamparser.h"
#include "parsers/spsparser.h"
#include "parsers/decodergeneralparser.h"
#include "parsers/cupuparser.h"
#include "parsers/tuparser.h"
#include "parsers/predparser.h"
#include "parsers/mvparser.h"
#include "parsers/mergeparser.h"
#include "parsers/intraparser.h"
#include "parsers/bitparser.h"
#include "parsers/tileparser.h"
#include "exceptions/decodingfailexception.h"
#include "gitlupdateuievt.h"
#include "gitlivkcmdevt.h"
#include <QDir>
#include <chrono>
#include <fstream>
#include <memory>
#include <filesystem>

class Timer {
private:
    QString msg;
    std::chrono::steady_clock::time_point start;
public:
    Timer(const QString& msg_) :msg(msg_) {
        start = std::chrono::high_resolution_clock::now();
    };
    ~Timer() {
        auto end = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
        qDebug() << QString("%1s %2").arg(duration.count() / 1000000.0, 0, 'f', 4).arg(msg);
    }
};

OpenBitstreamCommand::OpenBitstreamCommand(QObject *parent) :
    GitlAbstractCommand(parent)
{
}

class ParserInfo {
public:
    QString fileName;
    QString description;
    std::unique_ptr<InfoParser> pParser;
};

bool OpenBitstreamCommand::execute(GitlCommandParameter& rcInputArg, [[maybe_unused]] GitlCommandParameter& rcOutputArg)
{
    ModelLocator* pModel = ModelLocator::getInstance();

    /// *****STEP 0 : Request*****
    QVariant vValue;
    vValue = rcInputArg.getParameter("filename");
    QString strFilename = vValue.toString();
    vValue = rcInputArg.getParameter("version");
    int iVersion = vValue.toInt();
    vValue = rcInputArg.getParameter("skip_decode");
    bool bSkipDecode = vValue.toBool();
    QString strDecoderPath = "./decoders";
    QString strDecoderOutputPath = pModel->getPreferences().getCacheFolder();
    // int iSequenceIndex = pModel->getSequenceManager().getAllSequences().size();
    QFileInfo infoStreamFile = QFileInfo(strFilename);
    strDecoderOutputPath += QString("/%1").arg(infoStreamFile.baseName());




    /// show busy dialog
    GitlUpdateUIEvt evt;
    evt.setParameter("busy_dialog_visible", true);
    evt.dispatch();

    /// hide busy dialog when scope exit
    SCOPE_EXIT(GitlUpdateUIEvt evt;
    evt.setParameter("busy_dialog_visible", false);
    evt.dispatch();
        );


    //TODO BUG Memory Leaking when exception happens
    if (pModel->getSequenceManager().getSequenceByFilename(strFilename) != NULL)
    {
        qCritical() << "This bitstream is aleardy opened...";
        return false;
    }
    ComSequence* pcSequence = new ComSequence();
    pcSequence->init();
    pcSequence->setFileName(strFilename);

    /// *****STEP 1 : Use the special decoder to parse bitstream*****
    /// call decoder process to decode bitstream to YUV and output text info
    GitlUpdateUIEvt cDecodingStageInfo;
    bool bSuccess = false;
    if (!bSkipDecode)
    {
        Timer t("decoding finidshed");
        cDecodingStageInfo.setParameter("decoding_progress", "(1/11)Start Decoding Bitstream...");
        dispatchEvt(cDecodingStageInfo);
        BitstreamParser cBitstreamParser;
        bSuccess = cBitstreamParser.parseFile(strDecoderPath,
            iVersion,
            strFilename,
            strDecoderOutputPath,
            pcSequence);
        if (!bSuccess)
            throw DecodingFailException();
    }
    else
    {
        bSuccess = true;
        qDebug() << "decoding skiped";
    }


    /// *****STEP 2 : Parse the txt file generated by decoder*****
    /// Parse decoder_sps.txt
    QString strSPSFilename = strDecoderOutputPath + "/decoder_sps.txt";
    if (bSuccess)
    {
        Timer t("SPS file parsing finished");
        cDecodingStageInfo.setParameter("decoding_progress", "(2/11)Start Parsing Sequence Parameter Set...");
        dispatchEvt(cDecodingStageInfo);
        QFile cSPSFile(strSPSFilename);
        cSPSFile.open(QIODevice::ReadOnly);
        QTextStream cSPSTextStream(&cSPSFile);
        SpsParser cSpsParser;
        bSuccess = cSpsParser.parseFile(&cSPSTextStream, pcSequence);
        cSPSFile.close();

        QString strVPSFilenmae = strDecoderOutputPath + "/decoder_vps.txt";
        QFile cVPSFile(strVPSFilenmae);
        if (cVPSFile.open(QIODevice::ReadOnly)) {
            QTextStream cVPSTextStream(&cVPSFile);
            VpsParser cVpsParser;
            bSuccess = bSuccess && cVpsParser.parseFile(&cVPSTextStream, pcSequence);
            cVPSFile.close();
        }
    }
    /// Parse decoder_general.txt
    QString strGeneralFilename = strDecoderOutputPath + "/decoder_general.txt";
    if (bSuccess)
    {
        Timer t("Decoder general file parsing finished");
        cDecodingStageInfo.setParameter("message", "(3/11)Start Parsing Decoder Std Output File...");
        dispatchEvt(cDecodingStageInfo);
        std::ifstream cGeneralTextStream(strGeneralFilename.toLocal8Bit());
        DecoderGeneralParser cDecoderGeneralParser;
        bSuccess = cDecoderGeneralParser.parseFile(cGeneralTextStream, pcSequence);
    }

    ParserInfo infoFiles[] = {
        {"/decoder_cupu.txt", "CU & PU structure", std::make_unique<CUPUParser>()},
        {"/decoder_tu.txt","TU structure", std::make_unique<TUParser>()},
        {"/decoder_pred.txt", "Predtion Mode", std::make_unique<PredParser>()},
        {"/decoder_mv.txt", "Motion Vectors", std::make_unique<MVParser>()},
        {"/decoder_merge.txt","Motion Vector Merge", std::make_unique<MergeParser>()},
        {"/decoder_intra.txt","Intra Info", std::make_unique<IntraParser>()},
        {"/decoder_bit_lcu.txt","Bits LCU", std::make_unique<BitParserLCU>()},
        {"/decoder_bit_scu.txt", "Bits SCU", std::make_unique<BitParserSCU>()},
    };

    std::vector<StreamReader::TFileStore> fileStores;
    {
        Timer t("read bin file");
        QString strFilename = strDecoderOutputPath + "/decoder_info.bin";
        auto fileNameLocal = std::string(strFilename.toLocal8Bit());
        size_t fileSz = std::filesystem::file_size(fileNameLocal);
        std::ifstream stream(fileNameLocal, std::ios::binary);
        std::vector<char> fileContent(fileSz);
        stream.read(fileContent.data(), fileSz);
        fileStores = StreamReader::parse(fileContent.data(), pcSequence->getFramesInDisOrder().size(), pcSequence->getNumberMaxCu());
    }

    int step = 4;
    for (int i = 0; i < sizeof(infoFiles)/sizeof(ParserInfo); i++) {
        auto& parseInfo = infoFiles[i];
        if (bSuccess)
        {
            Timer t(parseInfo.description + " parsing finished");
            cDecodingStageInfo.setParameter("decoding_progress", QString("(%1/11)Start Parsing %2 ...").arg(step++).arg(parseInfo.description));
            dispatchEvt(cDecodingStageInfo);
            bSuccess = parseInfo.pParser->parseFile(std::move(fileStores[i]), pcSequence);
            pcSequence->addDelyedParser(std::move(parseInfo.pParser));
        }
    }

    ///*****STEP 3 : Open decoded YUV sequence*****
    pModel->getSequenceManager().addSequence(pcSequence);
    pcSequence->setYUVRole(YUV_RECONSTRUCTED);      /// display the recon. by default
    GitlIvkCmdEvt cSwitchSeq("switch_sequence");
    cSwitchSeq.setParameter("sequence", QVariant::fromValue((void*)pcSequence));
    cSwitchSeq.dispatch();

    return bSuccess;
}
